nome = str(input('Qual é o seu nome? '))
N = (nome.upper())
print(f'seu nome em letras maiúsculas {N}')
print('seu nome em letras maiúsculas', (nome.upper()))
print('seu nome em letras minúsculas', (nome.lower()))
nome2 = (''.join(nome.split()))
q = (len(nome2))
print(f'Seu nome possuí {q} letras.')
primeiro_nome = len(nome.split()[0])
print(f'A quantidade de letras do seu primeiro nome é {primeiro_nome}')
