n= int (input ('Digite um número ') )
print (n)
b= bool (input ('Digite um número ') )
print (b)
f= float (input ('Digite um número ') )
print (f)
s = str(input('Digite um número '))
print(s)
b2 = input('Digite algo ')
print(b2.isalnum())