print('COMEÇO AULA 07')
N1 = input('Um número ')
N2 = input('Outro número ')
s = (N1+N2)
print(f'A soma vale {s}')
print('SEGUNDO TESTE COMEÇANDO')
n1 = int(input('Um número '))
n2 = int(input('Um número '))
S = (n1+n2)
print(f'A soma vale {S}')
